files.extend-exclude = [
  "dev",
  "core/api/dev",
  "core/api/src/domain/users/languages.ts",
  "core/api/docker-compose.yml",
  "quickstart/*.yml",
  "quickstart/galoy",
  "quickstart/dev",
  "prelude",
  "core/notifications/locales/*.yml",
  "apps/admin-panel/components/notification/languages.ts",
  "apps/pay/components/success-animation.json",
]

default.extend-ignore-identifiers-re = [
  "^bc1\\w+",
  "^lnbc\\w+",
  "[Ww][Ss]",
]

default.extend-ignore-re = ["\"eyJ[a-zA-Z0-9_\\-\\.]+\""]

[default.extend-words]
# returned from twilio API referenced in src/debug/text-sms.ts
Ons = "Ons"
Lsat = "Lsat"
quizs = "quizs"
Aggrement = "Aggrement"
Governement = "Governement"
