files.extend-exclude = [
  "dev",
  "core/api/dev",
  "core/api/src/domain/users/languages.ts",
  "docs/postman-collection/galoy_graphql_main_api.postman_collection.json",
  "core/api/docker-compose.yml",
  "quickstart/*.yml",
  "quickstart/galoy",
  "quickstart/dev",
  "prelude",
  "core/api/test/e2e/servers/kratos.spec.ts",
]

default.extend-ignore-identifiers-re = [
  "^bc1\\w+",
  "^lnbc1\\w+",
]

default.extend-ignore-re = ["\"eyJ[a-zA-Z0-9_\\-\\.]+\""]

[default.extend-words]
# returned from twilio API referenced in src/debug/text-sms.ts
Ons = "Ons"
Lsat = "Lsat"
quizs = "quizs"