exchanges:
  okex:
    weight: 1.0

price_server:
  enabled: true
  server:
    listen_port: 3325
  fees:
    base_fee_rate: 0.0005
    immediate_fee_rate: 0.0005
    delayed_fee_rate: 0.0007
  price_cache:
    dev_mock_price_btc_in_usd: 20000

okex_price_feed:
  enabled: false

tracing:
  host: "otel-agent"
  port: 6831
  service_name: "stablesats-dev"

user_trades:
  enabled: false

hedging:
  enabled: false
