{{- range .Values.cron }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          containers:
          - name: {{ .name }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            {{- if .command }}
            command: ["/bin/sh","-c", {{ .command | quote }}]
            {{- end }}
            {{- if .args }}
            args: {{ .args }}
            {{- end }}
            volumeMounts:
            - name: firebase-serviceaccount
              mountPath: "/tmp/firebase-serviceaccount"
              readOnly: true
            - name: "custom-yaml"
              mountPath: "/var/yaml/"
            env:
            # TODO: refactor with a yaml template
            # dedupe with deployment.yaml
            - name: HELMREVISION
              value: {{ $.Release.Revision | quote}}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-mongodb
                  key: "mongodb-password"
            - name: MONGODB_USER
              value: "testGaloy"
            - name: MONGODB_ADDRESS
              value: {{ $.Values.mongodbaddress }}

            - name: LND1_DNS
              value: "lnd1"
            - name: LND1_MACAROON
              valueFrom:
                secretKeyRef:
                  name: lnd1-credentials
                  key: admin_macaroon_base64
            - name: LND1_TLS
              valueFrom:
                secretKeyRef:
                  name: lnd1-credentials
                  key: tls_base64
            - name: LND1_PUBKEY
              valueFrom:
                secretKeyRef:
                  name: lnd1-pubkey
                  key: pubkey

            - name: LND2_DNS
              value: "lnd2"
            - name: LND2_MACAROON
              valueFrom:
                secretKeyRef:
                  name: lnd2-credentials
                  key: admin_macaroon_base64
            - name: LND2_TLS
              valueFrom:
                secretKeyRef:
                  name: lnd2-credentials
                  key: tls_base64
            - name: LND2_PUBKEY
              valueFrom:
                secretKeyRef:
                  name: lnd2-pubkey
                  key: pubkey

            - name: BITCOINDADDR
              value: "bitcoind"
            - name: BITCOINDRPCPASS
              valueFrom:
                secretKeyRef:
                  name: bitcoind-rpcpassword
                  key: password
            - name: BITCOINDPORT
              value: {{ $.Values.bitcoind.port | quote }}

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-redis
                  key: "redis-password"
            - name: REDIS_MASTER_NAME
              value: "mymaster"
            - name: REDIS_0_DNS
              value: "galoy-redis-node-0.galoy-redis-headless"
            - name: REDIS_1_DNS
              value: "galoy-redis-node-1.galoy-redis-headless"
            - name: REDIS_2_DNS
              value: "galoy-redis-node-2.galoy-redis-headless"

            - name: LOGLEVEL
              value: debug
            - name: FTX_KEY
              valueFrom:
                secretKeyRef:
                  name: ftx-secret
                  key: key
            - name: FTX_SECRET
              valueFrom:
                secretKeyRef:
                  name: ftx-secret
                  key: secret
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/tmp/firebase-serviceaccount/galoyapp-firebase-serviceaccont.json"
            - name: DROPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dropbox-access-token
                  key: token
          restartPolicy: OnFailure
          volumes:
          - name: firebase-serviceaccount
            secret:
              secretName: galoyapp-firebase-serviceaccount
          - name: "custom-yaml"
            secret:
              secretName: "galoy-config-map"
      
---
{{- end }}
