{{- range $.Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/managed-by: Helm
    kube-monkey/enabled: enabled
    kube-monkey/identifier: {{.name}}
    kube-monkey/kill-mode: fixed
    kube-monkey/kill-value: "1"
    kube-monkey/mtbf: "8"
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      name: {{ .name }}
      labels:
        app: {{ .name }}
        kube-monkey/enabled: enabled
        kube-monkey/identifier: {{.name}}
    {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}{{- if .debugContainer -}}-debug{{- end -}}"
          {{- if .command }}
          command: ["/bin/sh","-c", {{ .command }}]
          {{- end }}
          {{- if .args }}
          args: {{ .args }}
          {{- end }}
          volumeMounts:
          {{- if $.Values.needFirebaseServiceAccount }}
          - name: firebase-serviceaccount
            mountPath: "/tmp/firebase-serviceaccount"
            readOnly: true
          {{- end}}
          {{- if eq .name "trigger" }}
          - name: "service-account"
            mountPath: "/var/secret/cloud.google.com"
          {{- end}}
          - name: "custom-yaml"
            mountPath: "/var/yaml/"
          {{- if .targetPort }}
          ports:
            - name: http
              containerPort: {{ .targetPort }}
              protocol: TCP
          {{- end }}
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          env:
            # TODO: refactor with a yaml template
            # dedupe with cronjob.yaml
            - name: HELMREVISION
              value: {{ $.Release.Revision | quote}}
            - name: NODE_ENV
              value: production
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-mongodb
                  key: "mongodb-password"
            - name: MONGODB_USER
              value: "testGaloy"
            - name: MONGODB_ADDRESS
              value: {{ $.Values.mongodbaddress }}

            - name: LND1_DNS
              value: "lnd1"
            - name: LND1_MACAROON
              valueFrom:
                secretKeyRef:
                  name: lnd1-credentials
                  key: admin_macaroon_base64
            - name: LND1_TLS
              valueFrom:
                secretKeyRef:
                  name: lnd1-credentials
                  key: tls_base64
            - name: LND1_PUBKEY
              valueFrom:
                secretKeyRef:
                  name: lnd1-pubkey
                  key: pubkey

            - name: LND2_DNS
              value: "lnd2"
            - name: LND2_MACAROON
              valueFrom:
                secretKeyRef:
                  name: lnd2-credentials
                  key: admin_macaroon_base64
            - name: LND2_TLS
              valueFrom:
                secretKeyRef:
                  name: lnd2-credentials
                  key: tls_base64
            - name: LND2_PUBKEY
              valueFrom:
                secretKeyRef:
                  name: lnd2-pubkey
                  key: pubkey

            - name: BITCOINDADDR
              value: "bitcoind"
            - name: BITCOINDRPCPASS
              valueFrom:
                secretKeyRef:
                  name: bitcoind-rpcpassword
                  key: password
            - name: BITCOINDPORT
              value: {{ $.Values.bitcoind.port | quote }}

            - name: GEETEST_ID
              value: "geetest_id"
            - name: GEETEST_KEY
              valueFrom:
                secretKeyRef:
                  name: geetest-key
                  key: geettest_key

            - name: REDIS_MASTER_NAME
              value: "mymaster"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-redis
                  key: "redis-password"
            - name: REDIS_0_DNS
              value: "galoy-redis-node-0.galoy-redis-headless"
            - name: REDIS_1_DNS
              value: "galoy-redis-node-1.galoy-redis-headless"
            - name: REDIS_2_DNS
              value: "galoy-redis-node-2.galoy-redis-headless"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: NETWORK
              valueFrom:
                secretKeyRef:
                  name: network
                  key: network
            {{- if $.Values.loglevel}}
            - name: LOGLEVEL
              value: {{ $.Values.loglevel }}
            {{- end}}
            {{- if $.Values.needFirebaseServiceAccount }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/tmp/firebase-serviceaccount/galoyapp-firebase-serviceaccont.json"
            {{- end }}
            {{- if eq .name "trigger" }}
            - name: "GCS_APPLICATION_CREDENTIALS"
              value: "/var/secret/cloud.google.com/galoyapp-31518a00082f.json"
            - name: DROPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dropbox-access-token
                  key: token
            {{- end }}
            {{- if eq $.Values.global.network "regtest" }}
            - name: MACAROONOUTSIDE1
              valueFrom:
                secretKeyRef:
                  name: lnd-outside-1-credentials
                  key: admin_macaroon_base64
            - name: TLSOUTSIDE1
              valueFrom:
                secretKeyRef:
                  name: lnd-outside-1-credentials
                  key: tls_base64
            - name: MACAROONOUTSIDE2
              valueFrom:
                secretKeyRef:
                  name: lnd-outside-2-credentials
                  key: admin_macaroon_base64
            - name: TLSOUTSIDE2
              valueFrom:
                secretKeyRef:
                  name: lnd-outside-2-credentials
                  key: tls_base64
            - name: LNDOUTSIDE1ADDR
              value: "lnd-outside-1"
            - name: LNDOUTSIDE2ADDR
              value: "lnd-outside-2"
            {{- else }}
            - name: APOLLO_GRAPH_VARIANT
              value: current
            - name: APOLLO_SCHEMA_REPORTING
              value: "true"
            - name: APOLLO_GRAPH_ID
              valueFrom:
                secretKeyRef:
                  name: galoy-apollo-secret
                  key: id
            - name: APOLLO_KEY
              valueFrom:
                secretKeyRef:
                  name: galoy-apollo-secret
                  key: key
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_PHONE_NUMBER
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_API_KEY
            - name: TWILIO_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: twilio-secret
                  key: TWILIO_API_SECRET
            - name: SMSALA_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: smsala-secret
                  key: SMSALA_SENDER_ID
            - name: SMSALA_API_ID
              valueFrom:
                secretKeyRef:
                  name: smsala-secret
                  key: SMSALA_API_ID
            - name: SMSALA_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smsala-secret
                  key: SMSALA_API_PASSWORD
            {{- end }}
          {{- if .healthz }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .targetPort }}
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: {{ .timeoutSeconds | default 1 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .targetPort }}
            initialDelaySeconds: 5
            failureThreshold: 5
            successThreshold: 2
            timeoutSeconds: {{ .timeoutSeconds | default 1 }}
          {{- end }}
      volumes:
      {{- if $.Values.needFirebaseServiceAccount }}
      - name: firebase-serviceaccount
        secret:
          secretName: galoyapp-firebase-serviceaccount
      {{- end}}
      {{- if eq .name "trigger" }}
      - name: "service-account"
        secret:
          secretName: "gcs-sa-key"
      {{- end}}
      - name: "custom-yaml"
        secret:
          secretName: "galoy-config-map"
---
{{- end }}
