apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "mongo-backup"
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
          - name: "mongodb-backup"
            image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
            command: ["/bin/sh","-c", "/var/backup.sh"]
            volumeMounts:
            - name: mongo-backup-configmap
              mountPath: "/var"
            - name: "service-account"
              mountPath: "/var/secret/cloud.google.com"
            env:
            - name: NETWORK
              valueFrom:
                secretKeyRef:
                  name: network
                  key: network
            - name: MONGODB_PASSWORD
              value: "testGaloy"
            - name: MONGODB_USER
              value: "testGaloy"
            - name: MONGODB_ADDRESS
              value: {{ $.Values.mongodbaddress }}
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DB
              value: "galoy"
            - name: DROPBOX_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dropbox-access-token
                  key: token
          restartPolicy: OnFailure
          volumes:
          - name: mongo-backup-configmap
            configMap:
              name: mongo-backup-configmap
              defaultMode: 484
          - name: "service-account"
            secret:
              secretName: "gcs-sa-key"
