global:
  network: regtest

jwtSecret: "my_non_secured_secret"

bitcoind:
  port:
    18443

redis:
  master:
    persistence:
      enabled: false
  metrics:
    enabled: false

nginx:
  enabled: false

mongodb:
  persistence:
    enabled: false
  replicaCount: 1
  metrics:
    enabled: false
  initDbScripts: {}

cron: []
deployment:
- name: graphql
  args: ["/lib/entrypoint/graphql.js"]
  healthz: true
  targetPort: 4000
  replicaCount: 1
- name: testpod
  replicaCount: 1
  debugContainer: "true"

needFirebaseServiceAccount: false
twilio: false

mongodbaddress: "galoy-mongodb-headless"

price:
  service:
    type: NodePort