# Definitions of third-party libraries used for Rust build of Galoy.
#
# Note: This file is **not** used by a regular Cargo build of Galoy.

[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Do-nothing target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

# List of packages to be imported, with version constraints, features and all
# options Cargo supports.
[dependencies]
anyhow = "1.0.82"
async-graphql = { version = "6.0.11", default-features = false, features = ["tracing", "chrono", "playground"] }
async-graphql-axum = "6.0.11"
axum = { version = "0.6.20", features = ["headers", "macros"] }
base64 = { version = "0.22.0" }
jsonwebtoken = "9.3.0"
clap = { version = "4.5.4", features = ["derive", "env"] }
derive_builder = "0.13.1"
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0.200", features = ["derive"] }
reqwest = { version = "0.11.27", default-features = false, features = ["json", "rustls-tls"] }
thiserror = "1.0.59"
serde_yaml = "0.9.33"
serde_json = "1.0.116"
chrono = { version = "0.4.38", features = ["clock", "serde"], default-features = false }
futures = "0.3.30"
sqlx = { version = "0.7.4", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
sqlxmq = { version = "0.5", default-features = false, features = ["runtime-tokio-rustls"] }
rand = "0.8.5"
uuid = { version = "1.8.0", features = ["serde", "v4"] }
serde_with = "3.8.1"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
tracing-opentelemetry = "0.20.0"
opentelemetry-otlp = { version = "0.13.0", features = ["http-proto", "reqwest-client"] }
opentelemetry = { version = "0.20.0", features = ["trace", "rt-tokio"]}
opentelemetry-semantic-conventions = "0.12.0"
opentelemetry-http = "0.9.0"
http = "0.2.12"
rust-i18n = "3"
google-fcm1 = "5.0.4"
lettre = { version = "0.11.7", default-features = false, features = ["builder", "tokio1", "tokio1-rustls-tls", "smtp-transport"] }
handlebars = "5.1.2"
rusty-money = { version = "0.4.1", features = ["iso", "crypto" ] }

prost = "0.12"
tonic = "0.10.2"
tonic-health = "0.10.2"
tonic-build = { version = "0.10.2", features = ["prost"] }

version_check = "0.9.4" # for some reason reindeer didn't auto-add this
