#@data/values
---
git_uri: git@github.com:GaloyMoney/galoy.git
git_branch: main
gh_repository: galoy
github_private_key: ((github.private_key))
docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))
git_charts_branch: main
git_charts_uri: git@github.com:GaloyMoney/charts.git
github_app_id: ((github.github_app_id))
github_app_private_key: ((github.github_app_private_key))
concourse_locks_git_uri: git@github.com:GaloyMoney/concourse-locks.git
