name: "Bats test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Bats tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Buck2 build
        run: |
          nix develop -c buck2 build //core/api:api //core/api-ws-server:api-ws-server \
            //core/api-keys:api-keys //apps/dashboard:dashboard //apps/consent:consent //apps/pay:pay
      - name: Run bats tests
        run: |
          nix develop -c bats --setup-suite-file bats/ci_setup_suite.bash -t bats/core/**
      - name: Rename Tilt log
        if: always()
        run: mv bats/.e2e-tilt.log bats/e2e-tilt.log
      - name: Upload Tilt log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Tilt log
          path: bats/e2e-tilt.log
