name: "Mobile Schema Compatibility"

on:
  pull_request:
    branches: [main]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      secret_exists: ${{ steps.secret_exists.outputs.defined }}
    steps:
      - name: Check for Secret availability
        id: secret_exists
        shell: bash
        run: |
          if [ "${{ secrets.MOBILE_DEPLOYMENTS_SSH_KEY }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  compatibility:
    name: Check mobile compatibility
    runs-on: ubuntu-latest
    needs: [check-secret]
    if: needs.check-secret.outputs.secret_exists == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: actions/checkout@v4
        with:
          repository: GaloyMoney/galoy-mobile-deployments
          ref: main
          fetch-depth: 0
          path: mobile-deployments
          ssh-key: ${{ secrets.MOBILE_DEPLOYMENTS_SSH_KEY }}
      - name: Check compatibility
        run: ./repo/ci/tasks/check-mobile-schema-compatibility.sh
