name: "Quickstart"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Quickstart
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: carvel-dev/setup-action@v1
        with:
          only: ytt, vendir
      - name: Test quickstart
        run: |
          cd quickstart
          ./bin/bump-galoy-git-ref.sh ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.head.repo.clone_url }}
          ./bin/bump-galoy-image-digest.sh api local
          ./bin/bump-galoy-image-digest.sh trigger local
          ./bin/bump-mongodb-migrate-image-digest.sh local
          make re-render
          source .envrc
          docker compose up -d
          ./bin/quickstart.sh
